#!/usr/bin/env bash
# Re-apply iOS Xcode-project patches that cannot be expressed in tauri.conf.json.
#
# src-tauri/gen/apple/ is git-ignored and fully regenerated by `tauri ios init`,
# so any edit made there is lost on regeneration. Run this script after every
# `npm run tauri ios init` (or any regeneration of gen/apple) to re-apply them.
#
# Currently applied:
#   - OTHER_LDFLAGS += -liconv -lz
#     libgit2 (via the git2 crate) references iconv and zlib symbols. cargo builds
#     the app as a static lib, so the final link is done by xcodebuild, which does
#     not auto-link these on iOS. Without them the link fails with undefined
#     symbols (_iconv_open, _inflate, ...).
#
# The NSFaceIDUsageDescription Info.plist key is handled natively via
# src-tauri/Info.ios.plist (Tauri merges it automatically) and needs no patch here.
set -euo pipefail

cd "$(dirname "$0")/.."
PROJ="gen/apple/project.yml"

if [ ! -f "$PROJ" ]; then
  echo "error: $PROJ not found. Run 'npm run tauri ios init' first." >&2
  exit 1
fi

if grep -q "OTHER_LDFLAGS" "$PROJ"; then
  echo "OTHER_LDFLAGS already present; nothing to patch."
else
  sed -i '' \
    's/\(EXCLUDED_ARCHS\[sdk=iphoneos\*\]: x86_64\)/\1\n        OTHER_LDFLAGS: $(inherited) -liconv -lz/' \
    "$PROJ"
  echo "Added OTHER_LDFLAGS (-liconv -lz) to $PROJ"
fi

( cd gen/apple && xcodegen generate )
echo "Regenerated Xcode project."
